update package d/llvm

diff --git a/d/llvm/llvm.SlackBuild.patch b/d/llvm/llvm.SlackBuild.patch
--- a/d/llvm/llvm.SlackBuild.patch
+++ b/d/llvm/llvm.SlackBuild.patch
@@ -1,5 +1,5 @@
---- a/llvm.SlackBuild	2018-07-07 19:11:30.880098612 +0100
-+++ b/llvm.SlackBuild	2018-07-08 15:20:20.801317024 +0100
+--- a/llvm.SlackBuild	2018-09-27 20:55:22.202863599 +0300
++++ b/llvm.SlackBuild	2018-09-27 21:08:03.648151976 +0300
 @@ -59,6 +59,9 @@
  elif [ "$ARCH" = "x86_64" ]; then
    SLKCFLAGS="-O2 -fPIC"
@@ -10,10 +10,24 @@
  else
    SLKCFLAGS="-O2"
    LIBDIRSUFFIX=""
-@@ -118,13 +121,18 @@
- # is fixed.
- zcat $CWD/clang_disable_pgo.patch.gz | patch -p1 --verbose || exit 1
+@@ -107,7 +110,7 @@
+ # clangd to avoid the failure. Any help with a proper fix is appreciated.
+ # I have not reported this upstream since I suspect that it's an artifact
+ # of our convoluted build method.
+-if [ $ARCH = i586 ] || [ $ARCH = i686 ]; then
++if [ $ARCH = i?86 ] || [ $ARCH = aarch64 ]; then
+   zcat $CWD/clang-tools-extra.no.clangd.diff.gz | patch -p1 --verbose --backup --suffix=.orig || exit 1
+ fi
  
+@@ -122,13 +125,26 @@
+ # by building clang with shared libs
+ zcat $CWD/n_clang_allow_BUILD_SHARED_LIBRARY.patch.gz | patch -p0 --verbose || exit 1
+ 
++export SLKCFLAGS="$SLKCFLAGS -fPIC -Wall -Wp,-D_FORTIFY_SOURCE=2 -fpermissive -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -fuse-ld=gold"
++export SLKCONFARGS="-DLLVM_HOST_TRIPLE=$ARCH-slackware-linux \
++                    -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON"
++export LDFLAGS="-Wl,-z,relro -Wl,--as-needed -Wl,-z,now"
++
 +CCOMPILER=gcc
 +CPPCOMPILER=g++
 +which clang > /dev/null 2>&1 && { CCOMPILER=clang ; CPPCOMPILER=clang++ ;}
@@ -26,6 +40,9 @@
    cmake \
 -    -DCMAKE_C_COMPILER="clang" \
 -    -DCMAKE_CXX_COMPILER="clang++" \
++    \
++    $SLKCONFARGS \
++    \  
 +    -DCMAKE_C_COMPILER="$CCOMPILER" \
 +    -DCMAKE_CXX_COMPILER="$CPPCOMPILER" \
      -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
