fix build d/llvm

diff --git a/d/llvm/llvm.SlackBuild.patch b/d/llvm/llvm.SlackBuild.patch
--- a/d/llvm/llvm.SlackBuild.patch
+++ b/d/llvm/llvm.SlackBuild.patch
@@ -1,5 +1,5 @@
---- a/llvm.SlackBuild	2018-09-27 20:55:22.202863599 +0300
-+++ b/llvm.SlackBuild	2018-09-27 21:08:03.648151976 +0300
+--- a/llvm.SlackBuild	2018-09-21 03:09:28.127002869 +0300
++++ b/llvm.SlackBuild	2018-09-27 22:27:54.546935353 +0300
 @@ -59,6 +59,9 @@
  elif [ "$ARCH" = "x86_64" ]; then
    SLKCFLAGS="-O2 -fPIC"
@@ -19,10 +19,14 @@
    zcat $CWD/clang-tools-extra.no.clangd.diff.gz | patch -p1 --verbose --backup --suffix=.orig || exit 1
  fi
  
-@@ -122,13 +125,26 @@
+@@ -122,13 +125,30 @@
  # by building clang with shared libs
  zcat $CWD/n_clang_allow_BUILD_SHARED_LIBRARY.patch.gz | patch -p0 --verbose || exit 1
  
++# https://bugs.llvm.org/show_bug.cgi?id=37668
++# Failed to build the latest LLVM 7.0 code on AARCH64 due to the _Float16 related issue
++xzcat failed-to-build-the-LLVM-7.0-code-on-AARCH64-due-to-the-_Float16-related-issue.patch.xz | patch -p1 --verbose || exit 1
++
 +export SLKCFLAGS="$SLKCFLAGS -fPIC -Wall -Wp,-D_FORTIFY_SOURCE=2 -fpermissive -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -fuse-ld=gold"
 +export SLKCONFARGS="-DLLVM_HOST_TRIPLE=$ARCH-slackware-linux \
 +                    -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON"
